class UtilsLanguages {
  UtilsLanguages._();

  static const list = [
    {"isoCode": "auto", "countryName": "Auto"},
    {"isoCode": "af", "countryName": "Afrikaans"},
    {"isoCode": "sq", "countryName": "Albanian"},
    {"isoCode": "am", "countryName": "Amharic"},
    {"isoCode": "ar", "countryName": "Arabic"},
    {"isoCode": "hy", "countryName": "Armenian"},
    {"isoCode": "az", "countryName": "Azerbaijani"},
    {"isoCode": "eu", "countryName": "Basque"},
    {"isoCode": "be", "countryName": "Belarusian"},
    {"isoCode": "bn", "countryName": "Bengali"},
    {"isoCode": "bs", "countryName": "Bosnian"},
    {"isoCode": "bg", "countryName": "Bulgarian"},
    {"isoCode": "ca", "countryName": "Catalan"},
    {"isoCode": "ceb", "countryName": "Cebuano"},
    {"isoCode": "ny", "countryName": "Chichewa"},
    {"isoCode": "zh-cn", "countryName": "Chinese Simplified"},
    {"isoCode": "zh-tw", "countryName": "Chinese Traditional"},
    {"isoCode": "co", "countryName": "Corsican"},
    {"isoCode": "hr", "countryName": "Croatian"},
    {"isoCode": "cs", "countryName": "Czech"},
    {"isoCode": "da", "countryName": "Danish"},
    {"isoCode": "nl", "countryName": "Dutch"},
    {"isoCode": "en", "countryName": "English"},
    {"isoCode": "eo", "countryName": "Esperanto"},
    {"isoCode": "et", "countryName": "Estonian"},
    {"isoCode": "tl", "countryName": "Filipino"},
    {"isoCode": "fi", "countryName": "Finnish"},
    {"isoCode": "fr", "countryName": "French"},
    {"isoCode": "fy", "countryName": "Frisian"},
    {"isoCode": "gl", "countryName": "Galician"},
    {"isoCode": "ka", "countryName": "Georgian"},
    {"isoCode": "de", "countryName": "German"},
    {"isoCode": "el", "countryName": "Greek"},
    {"isoCode": "gu", "countryName": "Gujarati"},
    {"isoCode": "ht", "countryName": "Haitian Creole"},
    {"isoCode": "ha", "countryName": "Hausa"},
    {"isoCode": "haw", "countryName": "Hawaiian"},
    {"isoCode": "iw", "countryName": "Hebrew"},
    {"isoCode": "hi", "countryName": "Hindi"},
    {"isoCode": "hmn", "countryName": "Hmong"},
    {"isoCode": "hu", "countryName": "Hungarian"},
    {"isoCode": "is", "countryName": "Icelandic"},
    {"isoCode": "ig", "countryName": "Igbo"},
    {"isoCode": "id", "countryName": "Indonesian"},
    {"isoCode": "ga", "countryName": "Irish"},
    {"isoCode": "it", "countryName": "Italian"},
    {"isoCode": "ja", "countryName": "Japanese"},
    {"isoCode": "jw", "countryName": "Javanese"},
    {"isoCode": "kn", "countryName": "Kannada"},
    {"isoCode": "kk", "countryName": "Kazakh"},
    {"isoCode": "km", "countryName": "Khmer"},
    {"isoCode": "ko", "countryName": "Korean"},
    {"isoCode": "ku", "countryName": "Kurdish (Kurmanji)"},
    {"isoCode": "ky", "countryName": "Kyrgyz"},
    {"isoCode": "lo", "countryName": "Lao"},
    {"isoCode": "la", "countryName": "Latin"},
    {"isoCode": "lv", "countryName": "Latvian"},
    {"isoCode": "lt", "countryName": "Lithuanian"},
    {"isoCode": "lb", "countryName": "Luxembourgish"},
    {"isoCode": "mk", "countryName": "Macedonian"},
    {"isoCode": "mg", "countryName": "Malagasy"},
    {"isoCode": "ms", "countryName": "Malay"},
    {"isoCode": "ml", "countryName": "Malayalam"},
    {"isoCode": "mt", "countryName": "Maltese"},
    {"isoCode": "mi", "countryName": "Maori"},
    {"isoCode": "mr", "countryName": "Marathi"},
    {"isoCode": "mn", "countryName": "Mongolian"},
    {"isoCode": "my", "countryName": "Myanmar (Burmese)"},
    {"isoCode": "ne", "countryName": "Nepali"},
    {"isoCode": "no", "countryName": "Norwegian"},
    {"isoCode": "ps", "countryName": "Pashto"},
    {"isoCode": "fa", "countryName": "Persian"},
    {"isoCode": "pl", "countryName": "Polish"},
    {"isoCode": "pt", "countryName": "Portuguese"},
    {"isoCode": "pa", "countryName": "Punjabi"},
    {"isoCode": "ro", "countryName": "Romanian"},
    {"isoCode": "ru", "countryName": "Russian"},
    {"isoCode": "sm", "countryName": "Samoan"},
    {"isoCode": "gd", "countryName": "Scots Gaelic"},
    {"isoCode": "sr", "countryName": "Serbian"},
    {"isoCode": "st", "countryName": "Sesotho"},
    {"isoCode": "sn", "countryName": "Shona"},
    {"isoCode": "sd", "countryName": "Sindhi"},
    {"isoCode": "si", "countryName": "Sinhala"},
    {"isoCode": "sk", "countryName": "Slovak"},
    {"isoCode": "sl", "countryName": "Slovenian"},
    {"isoCode": "so", "countryName": "Somali"},
    {"isoCode": "es", "countryName": "Spanish"},
    {"isoCode": "su", "countryName": "Sundanese"},
    {"isoCode": "sw", "countryName": "Swahili"},
    {"isoCode": "sv", "countryName": "Swedish"},
    {"isoCode": "tg", "countryName": "Tajik"},
    {"isoCode": "ta", "countryName": "Tamil"},
    {"isoCode": "te", "countryName": "Telugu"},
    {"isoCode": "th", "countryName": "Thai"},
    {"isoCode": "tr", "countryName": "Turkish"},
    {"isoCode": "uk", "countryName": "Ukrainian"},
    {"isoCode": "ur", "countryName": "Urdu"},
    {"isoCode": "uz", "countryName": "Uzbek"},
    {"isoCode": "ug", "countryName": "Uyghur"},
    {"isoCode": "vi", "countryName": "Vietnamese"},
    {"isoCode": "cy", "countryName": "Welsh"},
    {"isoCode": "xh", "countryName": "Xhosa"},
    {"isoCode": "yi", "countryName": "Yiddish"},
    {"isoCode": "yo", "countryName": "Yoruba"},
    {"isoCode": "zu", "countryName": "Zulu"},
  ];
}
