name: translator_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  path: ^1.8.2
  uuid: ^4.1.0
  async: ^2.9.0
  camera: ^0.10.5+5
  dash_flags: ^0.1.1
  translator: ^0.1.7
  share_plus: ^7.2.1
  collection: ^1.17.0
  flutter_tts: ^3.8.3
  rate_my_app: ^1.1.4
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.4
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  speech_to_text: ^6.1.1
  json_annotation: ^4.8.1
  package_info_plus: ^4.2.0
  flex_color_scheme: ^7.0.5
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.2
  permission_handler: ^10.0.0
  font_awesome_flutter: ^10.4.0
  google_mlkit_text_recognition: ^0.10.0
  google_mlkit_object_detection: ^0.10.0
  animated_bottom_navigation_bar: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.0
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
   - assets/object_detection_object_labeler_v1.tflite

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
